### ISSUE TITLE
No 404 error handling

### ISSUE THREAD

**Issue by xboxfly15** [mateothegreat/svelte5-router#18]
Hi, thank you for spending your time to make this, it's very useful.

Can you please add the ability to specific a 404 component that returns a 404 status code as well.

This would improve the user experience, letting them know they've reached a page that wasn't found and also search engines by returning 404 status code so they don't index a non-existent page.

**Comment by xboxfly15** [comment]
As a temporary measure, I'm using this.
In my routes array, I've added a prehook to the default/index route that checks if the window path matches my base path (Which is nothing), like so:
```js
const routes = [
  {
    path: "",
    component: Index,
    // Rubbish 404 handling
    pre: (route) => {
      // Check window path against base path "/"
      if (window.location.pathname === '/') {
        return route
      } else {
        return {
          path: "",
          component: Four0Four
        }
      }
    },
  },
]
```

And to get around not having a 404 status code, I have added this to my Four0Four component, so search engines do not index the site.
```html
<svelte:head>
  <meta name="robots" content="noindex">
</svelte:head>
```

**Comment by xboxfly15** [comment]
Also want to let you know, when I run `npm run build`/`vite build`
I get the following warning.
```
[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

@mateothegreat/svelte5-router@0.1.35

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

**Comment by RingOfStorms** [comment]
I was able to get this working with this route config:

```
  const routes: Route[] = [
    {
      path: "/$",
      component: Homepage,
    },
    {
      path: "/test1$",
      component: async () => import("./test1.svelte"),
    },
    {
      path: "/test2$",
      component: Test2,
    },
    {
      // 404 fallback on all other routes
      path: ".*",
      component: NotFound,
    },
  ];
```

**Comment by mateothegreat** [comment]
Updated docs to better explain 404 handling @ https://github.com/mateothegreat/svelte5-router?tab=readme-ov-file#not-found.

Thanks ya'll!

**Comment by flyncodes** [comment]
> > I was able to get this working with this route config:
> > ```
> >   const routes: Route[] = [
> >     {
> >       path: "/$",
> >       component: Homepage,
> >     },
> >     {
> >       path: "/test1$",
> >       component: async () => import("./test1.svelte"),
> >     },
> >     {
> >       path: "/test2$",
> >       component: Test2,
> >     },
> >     {
> >       // 404 fallback on all other routes
> >       path: ".*",
> >       component: NotFound,
> >     },
> >   ];
> > ```
> 
> This doesn't seem to work anymore. And https://github.com/mateothegreat/svelte5-router/blob/main/docs/statuses.md `statuses={{ [StatusCode.NotFound]: NotFound }}` does not work for me

I get this error in console
```
@mateothegreat_svelt….js?v=c1cb28a3:1301 Uncaught (in promise) TypeError: anchor.before is not a function

	in router.svelte
	in App.svelte

    at NotFound (NotFound.svelte:2:51)
    at App (App.svelte:42:56)

```
