### ISSUE TITLE
Initial Route Rendering

### ISSUE THREAD

**Issue by tbocek** [mateothegreat/svelte5-router#3]
I've been exploring Svelte 5's new features and playing with a template project that combines Svelte 5, RSBuild, and SSR: https://github.com/tbocek/svelte5-rsbuild-ssr-template. While integrating your library, I discovered and fixed some issues with route initialization and component lifecycle management.

#### Issue
The router wasn't properly rendering the initial route during startup.

#### Fix
[PR #2](https://github.com/mateothegreat/svelte5-router/pull/2) improves the router initialization by:
1. Moving route.run() to `$effect.pre` to ensure proper component mounting sequence
2. Using Svelte 5's `{#key}` block for proper component lifecycle management

**Comment by mateothegreat** [comment]
Hey @tbocek!

I tested your proposed changes and it ended up causing a runaway loop:
![Google Chrome-001208@2x](https://github.com/user-attachments/assets/d9b9bdc1-eef7-4490-b015-eb84795be946)

I did however incorporate your #key proposal, brilliant, and thank you! https://github.com/mateothegreat/svelte5-router/commit/a6ee64196becb77c7ff50848ab6aee4d2116acaa

Did ya have further concerns with `$effect.pre`?
-Matthew

**Comment by tbocek** [comment]
Interesting, when I tested the test folder on localhost, there was no loop. But I also don't see the path delayed in the test app. And I am currently having difficulties with making an account with Vercel, as it currently sais too many attempts please try later...

Anyway, I just pulled in your latest main ([71d13b7](https://github.com/mateothegreat/svelte5-router/commit/71d13b769af56a95beefdc81f00d5a94c6214cbb)), and now my hydrated svelte files work as intended 🎉. I saw that you moved the ```this.run(this.current);``` from the constructor in instance.svelte.ts to the router.svelte, where this is called now ```instance.run(...)```. I think this fixed it already, no need for ```effect.pre()```.

Thanks a lot for the quick fix and response!
