### ISSUE TITLE
Deep links do not work

### ISSUE THREAD

**Issue by popconst** [mateothegreat/svelte5-router#33]
<img width="1521" alt="image" src="https://github.com/user-attachments/assets/a034886a-53e4-42d2-a24b-b170b14d4745" />

What am I doing wrong here? Why the `keepers/manager` component never renders?

Feels like the deep links just won't work for me.

**Comment by popconst** [comment]
So it seems that the lib does not support deep links..
```
    { path: 'keepers', component: KeepersPage },
    { path: 'keepers-manager', component: KeepersManager },
```
  this way it works.

**Comment by dladlk** [comment]
Try to debug the method https://github.com/mateothegreat/svelte5-router/blob/cfd7c3a235beec42a2dfd89d5da51a731b44bf59/src/lib/instance.svelte.ts#L50 
It is a little fast-implementation as I see it. For deep links I switched to regex 
![image](https://github.com/user-attachments/assets/a7b86555-31bf-4b13-823f-2e7ed9416cbd)

**Comment by popconst** [comment]
this seems to work. thank you!

**Comment by mateothegreat** [comment]
all good!
