### ISSUE TITLE
How to work with another /basepath?

### ISSUE THREAD

**Issue by wa-rren-dev** [mateothegreat/svelte5-router#7]
I'm serving my app from a base path of `/myapp` so looking to set up routes and matchers that are always relative to that. I can't quite get the hang of the setup.

```
<script>
  const routes = [
    {
      path: `/`,
      component: Home,
    },
    {
      path: `new`,
      component: New,
    }
  ];

  function debug(route) {
      console.log(route);
      return route;
}
</script>

<a use:route href={`/`}>Home</a>
<a use:route href={`/new`}>New</a>

<Router base="/" {routes} pre={debug} />
```

If I do the above, all good. But my `base` in vite.config.js is set to "/myapp".

How would I amend the above to accommodate the basepath and also match the routes? I've tried all manner of combinations of putting the `myapp` prefix in the paths in the routes array, the base prop on the <Router>. Is there any info on doing this that I've missed?

Many thanks!

**Comment by popconst** [comment]
I'm also just using use vite and I'm not why the content does not change when I click a url. @wa-rren-dev  did you manage to find a fix?

**Comment by popconst** [comment]
my issue was that i was doing: 

```
  const routes: Route[] = [
    {
      path: '/swings',
      component: SwingStrategies
    }
  ]
  ```
  
  
  instaed i should have done
  
  ```
    const routes: Route[] = [
    {
      path: 'swings',
      component: SwingStrategies
    }
  ]
  ```

**Comment by wa-rren-dev** [comment]
> I'm also just using use vite and I'm not why the content does not change when I click a url. @wa-rren-dev did you manage to find a fix?

I didn't find a fix! Ended up stepping down to Svelte 4 for a few reasons.

**Comment by mateothegreat** [comment]
I got ya covered @wa-rren-dev! See #9.

Thanks for the feedback and the support <3

**Comment by mateothegreat** [comment]
> > I'm also just using use vite and I'm not why the content does not change when I click a url. @wa-rren-dev did you manage to find a fix?
> 
> I didn't find a fix! Ended up stepping down to Svelte 4 for a few reasons.

Please come back to the light of svelte 5!!!

**Comment by wa-rren-dev** [comment]
@mateothegreat Amazing thank you! Was thinking of porting to typescript so I'll give this a go when I do

**Comment by mateothegreat** [comment]
> @mateothegreat Amazing thank you! Was thinking of porting to typescript so I'll give this a go when I do

No problem man, you're welcome! Ping me and let me know how it goes!!
